### ISSUE TITLE
Dockerized version error

### ISSUE THREAD

**Issue by alexliit** [corvis/prana_rc#16]
Hello 
I just attempted to run the dockerized version and at the first API Call of the server (made by node-red docker instance on the same machine) I got a strange error on the Json response:

`org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
`
Since I'm quite new to the Docker "world" may be I'm missing something.

Thanks for any suggestions!

**Comment by corvis** [comment]
Hey @alexliit  I'm not quite sure but it looks like you have AppArmor configured to block unpriviliged access to DBUS which is required to interact with bluetooth stack. 

Try to add `--privileged` flag to `docker run` command

**Comment by alexliit** [comment]
Hello

I had to install also bluez
` sudo apt-get install bluez`
and now discover the prana devices of mine!

Let me know if you need support on testing on my devices (5 160 ERP Pro mini)

Thanks

Alex

**Comment by corvis** [comment]
Hey @alexliit great to see you've managed to set it up. I'll highly appreciate if you fill into this form: https://github.com/corvis/prana_rc/discussions/17 

And also it seems like your model supports VOC sensor which is not implemented in prana_rc yet because no one have such hardware. In order to implement support for the sensor I need 2-3 samples of the status output which could be extracted from the log. If you are willing to help I could instruct you how to get it and then implement VOC support
